version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
